# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Dragoncore/PipeLine/PipeLine.srcs/sources_1/ip/Instr_ROM_1/Instr_ROM.xci
# IP: The module: 'Instr_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dragoncore/PipeLine/PipeLine.srcs/sources_1/ip/Instr_ROM_1/Instr_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instr_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Dragoncore/PipeLine/PipeLine.srcs/sources_1/ip/Instr_ROM_1/Instr_ROM.xci
# IP: The module: 'Instr_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dragoncore/PipeLine/PipeLine.srcs/sources_1/ip/Instr_ROM_1/Instr_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instr_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
